### ISSUE TITLE
Cannot save or update a bean with multiple @Id

### ISSUE THREAD

**Issue by ufoscout** [ufoscout/jporm#61]
When trying to saveOrUpdate a bean with more than one @Id, the follwing exception is throw:

```
java.lang.RuntimeException: Cannot use this find method for class [eu.europa.ec.empl.eures.db.shared.model.domain.LabelTranslated]. Expected maximum one primary key field but found 2: [language, key]
    at com.jporm.session.SessionImpl.find(SessionImpl.java:141)
    at com.jporm.session.SessionImpl$6.now(SessionImpl.java:277)
    at 
```

This happens in 7.3 and it related to commit 18b5ec319519a0c1b24496c7300c5468f6faa027

**Comment by ufoscout** [comment]
Fixed in 7.3.x with d71e518
